name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/oddx/odd-game-server
          git checkout .
          git pull origin master
          npm install
          pm2 reload main